// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT BELOW THESE LINES
import "../styles/globals.css";
import Script from "next/script";
import type { AppProps } from "next/app";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      {/* INSTALLED APPS */}
      {/* LINKED APPS */}
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
