// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import type { NextPage } from "next";
import MicroFrontend from "../components/MicroFrontend";

const Home: NextPage = () => {
  return <MicroFrontend name={"Example"} host={"example"} />;
};

export default Home;
